const ESTADOS_RESERVA = {
  PENDIENTE: 'pendiente',
  APROBADA: 'aprobada',
  RECHAZADA: 'rechazada',
  CANCELADA: 'cancelada',
  FINALIZADA: 'finalizada',
};

const ESTADOS_ACTIVOS = [
  ESTADOS_RESERVA.PENDIENTE,
  ESTADOS_RESERVA.APROBADA,
];

const ESTADOS_TRANSITABLES = {
  [ESTADOS_RESERVA.PENDIENTE]: [ESTADOS_RESERVA.APROBADA, ESTADOS_RESERVA.RECHAZADA, ESTADOS_RESERVA.CANCELADA],
  [ESTADOS_RESERVA.APROBADA]: [ESTADOS_RESERVA.CANCELADA, ESTADOS_RESERVA.FINALIZADA],
  [ESTADOS_RESERVA.RECHAZADA]: [],
  [ESTADOS_RESERVA.CANCELADA]: [],
  [ESTADOS_RESERVA.FINALIZADA]: [],
};

module.exports = { ESTADOS_RESERVA, ESTADOS_ACTIVOS, ESTADOS_TRANSITABLES };
